#!/usr/bin/env python3
"""Generates an independent test vector for linked-device provisioning.

This is a separate implementation (Python `cryptography`, hand-written
protobuf encoding) of the *phone-side* encryption of a ProvisionMessage, written
from the algorithm in Signal-Desktop ts/textsecure/ProvisioningCipher.node.ts
(@abe80d3) and protos/DeviceMessages.proto. The Rust/WASM decryption in
crates/signal-web-core/src/provisioning.rs is tested against its output, so the
test does not merely round-trip one implementation through itself.

All keys and values are synthetic and test-only. The phone number uses the
fictional 555-01xx range.

Usage: python3 scripts/make_provisioning_vector.py > web/testdata/provisioning-vector.json
"""
import json
import os
import string
import uuid

from cryptography.hazmat.primitives import hashes, hmac, padding
from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.primitives.serialization import Encoding, NoEncryption, PrivateFormat, PublicFormat

DJB_TYPE = b"\x05"  # libsignal's type byte for Curve25519 public keys


def raw_priv(k):
    return k.private_bytes(Encoding.Raw, PrivateFormat.Raw, NoEncryption())


def raw_pub(k):
    return DJB_TYPE + k.public_key().public_bytes(Encoding.Raw, PublicFormat.Raw)


def varint(n):
    out = bytearray()
    while True:
        b = n & 0x7F
        n >>= 7
        out.append(b | (0x80 if n else 0))
        if not n:
            return bytes(out)


def field_bytes(num, value):
    if isinstance(value, str):
        value = value.encode()
    return varint(num << 3 | 2) + varint(len(value)) + value


def field_varint(num, value):
    return varint(num << 3 | 0) + varint(value)


def main():
    recipient = X25519PrivateKey.generate()      # the new linked device (browser)
    ephemeral = X25519PrivateKey.generate()      # the phone's per-link key
    aci_identity = X25519PrivateKey.generate()   # account identity being shared

    aci = str(uuid.uuid4())
    number = "+12025550123"
    code = "".join(os.urandom(1).hex() for _ in range(8))
    profile_key = os.urandom(32)
    aep = "".join(string.ascii_lowercase[b % 26] for b in os.urandom(64))

    message = b"".join([
        field_bytes(1, raw_pub(aci_identity)),       # aciIdentityKeyPublic
        field_bytes(2, raw_priv(aci_identity)),      # aciIdentityKeyPrivate
        field_bytes(3, number),                      # number
        field_bytes(4, code),                        # provisioningCode
        field_bytes(5, "OWP"),                       # userAgent
        field_bytes(6, profile_key),                 # profileKey
        field_varint(7, 1),                          # readReceipts
        field_bytes(8, aci),                         # aci
        field_varint(9, 1),                          # provisioningVersion
        field_bytes(15, aep),                        # accountEntropyPool
        field_bytes(17, uuid.UUID(aci).bytes),       # aciBinary
    ])

    shared = ephemeral.exchange(recipient.public_key())
    okm = HKDF(algorithm=hashes.SHA256(), length=64, salt=b"\x00" * 32,
               info=b"TextSecure Provisioning Message").derive(shared)
    aes_key, mac_key = okm[:32], okm[32:]
    iv = os.urandom(16)
    padder = padding.PKCS7(128).padder()
    padded = padder.update(message) + padder.finalize()
    enc = Cipher(algorithms.AES(aes_key), modes.CBC(iv)).encryptor()
    ciphertext = enc.update(padded) + enc.finalize()
    version_iv_ct = b"\x01" + iv + ciphertext
    mac = hmac.HMAC(mac_key, hashes.SHA256())
    mac.update(version_iv_ct)
    body = version_iv_ct + mac.finalize()

    envelope = field_bytes(1, raw_pub(ephemeral)) + field_bytes(2, body)

    print(json.dumps({
        "note": "Synthetic, test-only keys and values generated by scripts/make_provisioning_vector.py",
        "recipient_private_key_hex": raw_priv(recipient).hex(),
        "recipient_public_key_hex": raw_pub(recipient).hex(),
        "envelope_hex": envelope.hex(),
        "expected": {
            "aci": aci,
            "number": number,
            "provisioning_code": code,
            "profile_key_hex": profile_key.hex(),
            "account_entropy_pool": aep,
            "aci_identity_public_hex": raw_pub(aci_identity).hex(),
        },
    }, indent=2))


if __name__ == "__main__":
    main()
